# Generated by Django 2.0.3 on 2018-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180411_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='viewed_num',
            field=models.IntegerField(default=0),
        ),
    ]
